version: '3'
services:

  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
      - ./migrations/2023-07-23-091722_init/up.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
